[project]
name = "vectorsearch"
version = "0.1.0"
description = "vector search with a twist"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "faiss-cpu>=1.13.2",
    "gensim>=4.4.0",
    "ipykernel>=7.1.0",
    "numpy>=2.4.0",
    "sentence-transformers>=5.2.0",
    "sentencepiece>=0.2.1",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
